service: TfLambda-arxiv

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  
provider:
  name: aws
  region: us-east-1
  runtime: python3.6
  stage: dev
  #credentials:
  #  accessKeyId: 
  #  secretAccessKey: 

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
       Fn::Join:
         - ""
         - - "arn:aws:s3:::"
           - ${self:provider.environment.BUCKET}
           - "/*"
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - lambda:InvokeFunction 
        - lambda:GetLayerVersion
        - sagemaker:UpdateEndpoint
        - sagemaker:CreateModel
        - sagemaker:CreateEndpointConfig
        - sagemaker:DescribeEndpoint
        - sagemaker:CreateTrainingJob
        - sagemaker:InvokeEndpoint
      Resource:
        - arn:aws:dynamodb:eu-west-1:*:*
        - arn:aws:lambda:eu-west-1:*:* 
        - arn:aws:dynamodb:us-east-1:*:*
        - arn:aws:lambda:us-east-1:*:* 
        - arn:aws:iam::014011337545:user/serverless

  environment:
    BUCKET: serverless-ml-1

package:
  exclude:
    - model_ML.h5
    - model_ML_old.h5
    - data/2015ml.h5
    - data/2016ml.h5
    - data/2017ml.h5
    - data/2018ml.h5
    - data/2019ml.h5


functions:
  app:
    handler: wsgi.handler
#    layers:
#      - arn:aws:lambda:us-east-1:446751924810:layer:python-3-6-scikit-learn-0-22-0:4
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'


custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    noDeploy:
      - boto3
      - botocore
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - s3transfer
      - setuptools
      - six
      - tensorboard
  wsgi:
    app: app.app
    pythonBin: python3 # Some systems with Python3 may require this
    packRequirements: false


resources:
  Resources:
    SageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET}
